[package]
name = "ffs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
async-trait = "0.1.89"
bs58 = "0.5.1"
clap = { version = "4.6.1", features = ["cargo", "derive", "env", "wrap_help"] }
derive_more = { version = "2.1.1", features = ["full"] }
indoc = "2.0.7"
inquire = "0.9.4"
rkyv = { version = "0.8.17", features = ["uuid-1"] }
tabled = "0.21.0"
tempfile = "3.27.0"
tokio = { version = "1.52.3", features = ["full"] }
uuid = { version = "1.24.0", default-features = false, features = ["v4"] }
weighted-rs = "0.1.3"
